name: publish-ci-test
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, ready_for_review, synchronize]
    branches-ignore:
      - '*'
  push:
    branches-ignore:
      - '*'
      - '!master'
jobs:
  build-job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Validate Charts
        run: |
          sudo sh install-helm.sh
          alias helm="/tmp/helm/bin/linux-amd64/helm"
          sudo helm template charts/controller -f charts/controller/values.yaml
          sudo helm template charts/datastore -f charts/datastore/values.yaml
      - name: Publish Charts
        run: |
          sudo apt install jq curl -y
          echo $GITHUB_PAGES_REPO
          echo $GITHUB_BRANCH
          sudo sh publish.sh $GITHUB_PAGES_REPO $GITHUB_BRANCH $GITHUB_USERNAME
        env:
          GITHUB_PAGES_REPO: rookout/helm-charts
          GITHUB_BRANCH: ${{ github.ref }}
          GITHUB_USERNAME: sonariorobot
          GITHUB_PAGES_TEST: Goobensio/test
          
      - name: Verify - Published Charts
        run: |
          echo $GITHUB_BRANCH
          alias helm="/tmp/helm/bin/linux-amd64/helm"
          if [ "$GITHUB_BRANCH" = "refs/heads/master" ]; then
            echo "Waiting for repository to be updated before checking"
            sudo sleep 15
            helm repo add rookout https://helm-charts.rookout.com
            helm repo update
            helm repo list
            helm inspect chart rookout/controller
            helm inspect chart rookout/datastore
          fi
          echo $GITHUB_BRANCH
        env:
          GITHUB_BRANCH: ${{ github.ref }}
          
