# This is a basic workflow to help you get started with Actions

name: test-CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, ready_for_review, synchronize]
    branches-ignore:
      - main #'!main'
      - '!*'
  push:
    branches-ignore:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   verify-label-exist:
#     if: ${{ github.event.label.name != 'bug'}} # Lets say for example that bug is valid
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: check for labels
#         run: |
#           echo Valid label does not exist
#           exit 1 "failed to find label"
  build-job:
    #if: ${{ github.event.label.name == 'bug'}}
    #echo "::set-output name=action_fruit::strawberry"
    # The type of runner that the job will run on
    #if: ${{ github.event.label.name != 'bug'}} # Lets say for example that bug is valid
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: label check
        if: ${{ github.event.label.name != 'bug'}}
        uses: actions/checkout@v2
        with:
          script: |
              core.setFailed('valid label does not exist, please add one')
              exit 1
#       - name: check for labels
#         run: |
#           echo Valid label does not exist
#           exit 1 "failed to find label"
      #- with:
      #    valid-labels: 'bug, enhancement'
      #    invalid-labels: 'help wanted, invalid'
      # Runs a single command using the runners shell
        #if: ${{ github.event.label.name == 'bug'}}
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
