# This is a basic workflow to help you get started with Actions


# Controls when the workflow will run
name: validate-helm-charts-workflow
  # Triggers the workflow on push or pull request events but only for the main branch
on: 
  push:
    branches: [ '!master' ]
  pull_request:
    branches: [ '!master' ]
jobs:
  validate-helm-charts:
    #if: contains( github.event.pull_request.labels.*.name, 'My Label')
    if: github.event.label.name == 'controller' || github.event.label.name == 'datastore' || github.event.label.name == 'operator'
    runs-on: alpine
    steps:
      - uses: actions/checkout@v2
      - name: Validate Charts
        run: |
          sh install-helm.sh
          alias helm=/tmp/helm/bin/linux-amd64/helm
          helm template charts/controller -f charts/controller/values.yaml
          helm template charts/datastore -f charts/datastore/values.yaml
      - name: Validate Helm charts and compare with labels
        run: |
          apk add --no-cache jq 
          apk add --no-cache curl
          sh validate.sh
        env:
          GITHUB_PAGES_REPO: rookout/helm-charts 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
